version: '2'
services:
    semanticcumtdemo-app:
        image: semanticcumtdemo
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://semanticcumtdemo-postgresql:5432/SemanticCUMTDemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    semanticcumtdemo-postgresql:
        extends:
            file: postgresql.yml
            service: semanticcumtdemo-postgresql
